quarkus.application.version=1.0.1
quarkus.application.ui-header=DNSPEX
quarkus.test.continuous-testing=disabled
quarkus.banner.enabled=false

quarkus.log.console.format=[%d{HH:mm:ss}] %-5p> %s%e%n
quarkus.log.level=INFO

%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.datasource.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dnspex
quarkus.datasource.username=user
quarkus.datasource.password=pass

quarkus.log.sentry.enabled=true
quarkus.log.sentry.in-app-packages=*
quarkus.log.sentry.debug=true
quarkus.log.sentry.dsn=https://042733524e069c186383eed615d15420@o4511598016004096.ingest.de.sentry.io/4511598029832272
%dev.quarkus.log.sentry.environment=development
%prod.quarkus.log.sentry.environment=production

mp.jwt.verify.publickey.location=ssl/DNSPEX_OPENSSL_20_06_2026_PUBLIC.pem
smallrye.jwt.sign.key.location=ssl/DNSPEX_OPENSSL_20_06_2026_PRIVATE.pem
mp.jwt.verify.issuer=https://dnspex.com

%dev.resend.enabled=true
resend.enabled=true
resend.domain=dnspex.com
resend.api-key=re_KPUrV1QG_D9FjTGzrCPRZc6h5k6kZt4Yu

