quarkus.application.version=1.0.1
quarkus.application.ui-header=DNSPEX
quarkus.test.continuous-testing=disabled
quarkus.live-reload.instrumentation=true
quarkus.banner.enabled=false

quarkus.log.console.format=[%d{HH:mm:ss}] %-5p> %s%e%n
quarkus.log.level=INFO

%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD

quarkus.http.auth.proactive=false

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://db.schweizr.local:5432/dnspex
quarkus.datasource.username=postgres
quarkus.datasource.password=schweizer

quarkus.log.sentry.enabled=true
quarkus.log.sentry.in-app-packages=*
#quarkus.log.sentry.debug=true
quarkus.log.sentry.dsn=https://042733524e069c186383eed615d15420@o4511598016004096.ingest.de.sentry.io/4511598029832272
#%dev.quarkus.log.sentry.environment=development
#%prod.quarkus.log.sentry.environment=production

mp.jwt.verify.publickey.location=ssl/DNSPEX_OPENSSL_20_06_2026_PUBLIC.pem
smallrye.jwt.sign.key.location=ssl/DNSPEX_OPENSSL_20_06_2026_PRIVATE.pem
mp.jwt.verify.issuer=https://dnspex.com

%dev.resend.enabled=true
resend.enabled=true
resend.domain=dnspex.com
resend.api-key=re_KPUrV1QG_D9FjTGzrCPRZc6h5k6kZt4Yu

dnspex.session.delete.interval=0 0 2 * * ?
dnspex.domain.validation.interval=0 0 12 * * ?
dnspex.account.delete.interval=0 0 3 * * ?
dnspex.scheduled.default.timezone=Europe/Berlin